__version__ = "4.0.2"
__original_author__ = "Nico Schlömer"
__original_author_email__ = "nico.schloemer@gmail.com"
__copyright__ = "Copyright (c) 2015-2020 meshio developers"
__website__ = "https://github.com/nschloe/meshio"
__license__ = "License :: OSI Approved :: MIT License"
__status__ = "Development Status :: 5 - Production/Stable"
